### ISSUE TITLE
muk_utils tools/json.py module import itself?

### ISSUE THREAD

**Issue by Wertusser** [muk-it/muk_base#21]
Hi, trying to load muk_session_store, which depends on muk_utils. Throw exception
```
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/service/server.py", line 913, in load_server_wide_modules
web_1  |     odoo.modules.module.load_openerp_module(m)
web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 374, in load_openerp_module
web_1  |     getattr(sys.modules['odoo.addons.' + module_name], info['post_load'])()
web_1  |   File "/mnt/extra-addons/muk_session_store/__init__.py", line 27, in _patch_system
web_1  |     from . import patch
web_1  |   File "/mnt/extra-addons/muk_session_store/patch/__init__.py", line 23, in <module>
web_1  |     from . import http
web_1  |   File "/mnt/extra-addons/muk_session_store/patch/http.py", line 30, in <module>
web_1  |     from odoo.addons.muk_utils.tools.patch import monkey_patch
web_1  |   File "/usr/lib/python2.7/dist-packages/odoo/modules/module.py", line 81, in load_module
web_1  |     execfile(modfile, new_mod.__dict__)
web_1  |   File "/mnt/extra-addons/muk_utils/__init__.py", line 23, in <module>
web_1  |     from . import models
web_1  |   File "/mnt/extra-addons/muk_utils/models/__init__.py", line 23, in <module>
web_1  |     from . import base
web_1  |   File "/mnt/extra-addons/muk_utils/models/base.py", line 28, in <module>
web_1  |     from odoo.addons.muk_utils.tools import utils
web_1  |   File "/mnt/extra-addons/muk_utils/tools/__init__.py", line 25, in <module>
web_1  |     from . import json
web_1  |   File "/mnt/extra-addons/muk_utils/tools/json.py", line 35, in <module>
web_1  |     class ResponseEncoder(json.JSONEncoder):
web_1  | AttributeError: 'module' object has no attribute 'JSONEncoder'
```
Perhaps the problem lies in the name of the module "json.py". When i renamed it to json_patch.py via Pycharm, everything started to work again

**Comment by keshrath** [comment]
Please tell me the Odoo version and steps to reproduce the error,

**Comment by Wertusser** [comment]
Odoo version 12. I use docker-compose to start Odoo
docker-compose.yml
```
version: '3'
services:
  web:
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    command: -- --load=web,muk_session_store
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo

```
Clone this repository, move all addons to /addons directory, create /config directory with file odoo.conf
odoo.conf
```
[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
session_store_database = True
```
And start via docker-compose
```
docker-compose up --build
```
